### ISSUE TITLE
Different sources

### ISSUE THREAD

**Issue by Yaraslaut** [spinsphotonics/fdtdz#12]
Hi, thanks for the great tool :) 
At the moment I see that only dipole sources are implemented, and there is no easy way for user to create a point source or am i missing something? So I'm wondering if other sources like point, plane wave, gausian will be implemented? 

Also, what should I do if I want to calcualte structures that are longer in z direction than restriction for the grid size?

And maybe last question :) 
How I can take snapshots of field distribution at some time ?

**Comment by jlu-spins** [comment]
Hi @Yaraslaut!

- Plane sources are implemented, but unfortunately at this time you have to code the distribution (Gaussian, waveguide mode, ...) yourself. fdtd-z is still *really* low-level. That said, please see https://github.com/spinsphotonics/utilz/blob/main/src/utilz/modes.py for my mode computing code.

- Unfortunately, the z-dimension of the simulation domain is a hard limit in fdtd-z that is currently an absolutely fundamental (for performance reasons) assumption in the code.

- Snapshotting can be controlled via the `output_steps` parameter of `fdtdz_jax.fdtdz()`.

Hope this helps! Please keep the questions coming!

**Comment by Yaraslaut** [comment]
Thanks for the answer @jlu-spins, I think that i can close the issue and open new one if will face any chalanges :)

Since you plan to keep fdtdz very low-level, are you also planning to implement some wrapper package?

**Comment by jlu-spins** [comment]
Yes, currently working on https://github.com/spinsphotonics/pjz with inverse design as the target application.
