### ISSUE TITLE
Incorrect dipole test output?

### ISSUE THREAD

**Issue by smhooten** [spinsphotonics/fdtdz#24]
Hello, thanks for sharing this nice project. I wonder if there is an issue with the dipole test case on the Colab notebook, or if I need to adjust some settings? I am seeing the output below. I got the same output in my local installation of fdtd-z.
![image](https://github.com/spinsphotonics/fdtdz/assets/43480548/9101201d-26c8-4311-aa59-b28b859aeb18)

**Comment by jlu-spins** [comment]
Hi Sean! Sorry about the slow reply. You're seeing reflections from the PML
in your dipole output. The PML coefficients can be tuned to work better,
but I think there is some bug with the current implementation
unfortunately, created an issue at
https://github.com/spinsphotonics/fdtdz/issues/19

**Comment by smhooten** [comment]
Got it, thanks Jesse. I'll play around with the settings myself. I will close the issue for the time being since it is already known.
