### ISSUE TITLE
wrong shape constraint on PML parameters?

### ISSUE THREAD

**Issue by flaport** [spinsphotonics/fdtdz#27]
Hi! It's me again 🙂

Maybe I'm a little bit confused, but currently `fdtdz_jax` seems to require the pml parameters `pml_kappa`, `pml_sigma` and `pml_alpha` to be of shape `128-sum(pml_widths)`. is this correct? I would expect these pml parameters to extend all the way to the edges of the z-space.

**Comment by flaport** [comment]
Or is it because a PML is more memory intensive that the z-span needs to be reduced further?

**Comment by JesseLu** [comment]
No this is correct. Each layer of pml cost an additional layer of overhead
in z.

**Comment by flaport** [comment]
Thanks!
