### ISSUE TITLE
CUDA_ERROR_OUT_OF_MEMORY: out of memory

### ISSUE THREAD

**Issue by Guowu-Mcgill** [spinsphotonics/fdtdz#8]
Hey Jesse,

Thanks for this excellent open source. I tried on my end with an Nvidia GTX 3060 GPU (12 Gb Memory).

The installation finished properly without any errors. However, when I try out the example, I got warnings like below until the program failed (see below for detail). It seems the code fails because of insufficient memory. So, I tried to reduce the simulation grid cells to 100 * 100 * 100, but, the program gives me another error and still fails. 

Do you have any idea about possible reasons/solutions to this? Many thanks!

![image](https://user-images.githubusercontent.com/65426870/235943303-23896aec-9955-4ad4-9744-ac02f4aa532c.png)

with the same grid as the example,
![image](https://user-images.githubusercontent.com/65426870/235943686-29a9cff1-758c-48e9-b864-0d0f0258b2d4.png)

with a grid size of 100 * 100 * 100 cells,
![image](https://user-images.githubusercontent.com/65426870/235946376-f771d53f-fb57-496e-9e29-1e6845cdc77c.png)

Regards,
Guowu

**Comment by jlu-spins** [comment]
Thanks for bringing this up Guowu! 

As expected, the speed and size of simulations does depend on the GPU that you are using. Specifically, the `(gridu, gridv)` parameters not attempt to use more than the number of SMs which are on your GPU (`gridu * gridv < total # SMs on GPU`).

Also wrote up an answer to this at https://github.com/spinsphotonics/fdtdz/blob/main/README.md#cuda_error_cooperative_launch_too_large

Hope that helps!

**Comment by Guowu-Mcgill** [comment]
Hey Jesse,

Many, many thanks for this help! 

It works pretty well after I modified (gridu, gridv) parameters. Thanks!!!

Regards,
Guowu
